# See https://docs.codecov.io/docs/commit-status
coverage:
  status:
    project:
      default: false
      app:
        threshold: 1
        paths: "!tests/"
      tests:
        target: 100%
        paths: tests/
    patch:
      app:
        target: 50%
        paths: "!tests/"
